---
id: db-tech-showcase-tokyo-2017
base_name: mysql-postgresql-rich-full-text-search-system
tags:
- rabbit
- mysql
- mariadb
- postgresql
- mroonga
- pgroonga
- groonga
- dbts2017
presentation_date: 2017-09-07
version: 2017.9.7.0
licenses:
- CC-BY-SA-4.0
- CC-BY-3.0
slideshare_id: dbtechshowcasetokyo2017
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: 須藤功平
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: 
